# Szi Kay Leung 
# Aim: Loop samples through RNAseqvsIsoSeq_Template.Rmd
# 19/03/2020: Cleaned up script 

# load libraries
library(knitr)
library(readr)
library(dplyr)

# Loop samples through RNASeqvsIsoSeq_Template.Rmd to produce individual Rmarkdowns/sample  
samplelist <- c("K17", "K23", "M21", "O23", "Q21", "S23")
for (sample in samplelist) {
rmarkdown::render(input = "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Scripts/IsoSeq3_Tg4510/RNASeqvsIsoSeq/RNAseqvsIsoSeq_Template.Rmd", 
                  params = list(Sample = sample),
                  output_file = paste0(sample,"_IsoseqRNASeq.html"),
                  output_dir = "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/RNASeq/Correlations")
}


# Loop Sample_Full_Merge.csv files (output from the RNASeqvsIsoSeq/RNAseqvsIsoSeq_Template.Rmd) to generate the correlation plot (saved into one pdf) 
output_dir <- "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/RNASeq/Correlations"
all_Full_Merge <- list.files(path = output_dir, pattern = "_Full_Merge.csv", full.names = TRUE)
source("/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Scripts/IsoSeq3_Tg4510/RNASeqvsIsoSeq/RNASeqvsIsoSeq_Functions.R")

for (file in all_Full_Merge){
  print(file)
  
  df <- read.csv(file, header = TRUE)[,-1] #remove first column of index from import
  print(cor.test(df$Isoseq_FL_Counts, df$RNASeq_Raw_Counts, method = "pearson"))
  
  #pdf(paste0(output_dir,"AllSamples.pdf"))
  density_plot(df, "Isoseq_FL_Counts", "RNASeq_Raw_Counts")
  #print(Corplot)
  #print(Missing_Reads_Plot(df))
  #dev.off()
}
 

# Running individual samples through all the functions 
# for (sample in samplelist) {
#   sample
#   source("/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Scripts/IsoSeq3_Tg4510/RNASeqvsIsoSeq.R")
#   SQANTI_input(sample)
#   TOFU_input(sample)
#   Annotate2Abundance_IsoSeq(sample,classification_dat,abundance_dat)
#   Input_RNAseq(sample)
#   Merge_RNASeq_Isoseq(Merge_IsoSeq_SumFL,RNASeq) # output file name = Full_Merge
#   Missing_Reads_Review()
# }

