---
title: "IsoSeq Summary"
author: Szi Kay Leung
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=paste0("/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/WholeTranscriptome/Testing/Rmarkdowns",
                        '/IsoSeq_Summary.html')) })
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE) #,fig.width=14, fig.height= 7)
#rmarkdown::render("/gpfs/ts0/home/sl693") 

suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(stringr)) 
suppressMessages(library(tidyr))
suppressMessages(library(scales))
suppressMessages(library(rjson))
suppressMessages(library(magrittr))
suppressMessages(library(tibble))

#font_import()
```


```{r input}
# Input Directory Paths
CCS_input_dir <- "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Isoseq_Paper/QC/CCS_output/mouse"
LiMA_input_dir <- "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Isoseq_Paper/QC/ISOSEQ3_output"
ISOSEQ_input_dir <- "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/WholeTranscriptome/WT8_ISOSEQ/IsoSeq3.2.1/Isoseq3_WKD"

# CCS, LIMA summary 
CCS <- read.csv(paste0(CCS_input_dir, "/WT8Mouse_Individual_CCS_output.csv"), header = T)
LIMA <- read.csv(paste0(LiMA_input_dir, "/WT8Mouse_Individual_LIMA_summary.csv"), header = T)

# REFINE summary input 
REFINE_json_list <- list.files(paste0(ISOSEQ_input_dir), pattern = "flnc.filter_summary.json", full.names = T)
REFINE_list <- lapply(REFINE_json_list , function(x) as.data.frame(fromJSON(file = x)))
names(REFINE_list) <- list.files(paste0(ISOSEQ_input_dir), pattern = "flnc.filter_summary.json")
for(i in 1:length(names(REFINE_list))){
  REFINE_list[[i]]$Sample <- paste(word(names(REFINE_list)[[i]], c(1), sep = fixed ('.')))
}

```
```{r functions}
# input_multiple_csv 
input_multiple_csv <- function(input_dir_path, str_pattern){
  dat_files <- list.files(paste0(input_dir_path), pattern = str_pattern, full.names = T)
  dat <- lapply(dat_files, function(x) read.csv(x))
  names(dat) <- list.files(paste0(input_dir_path), pattern = str_pattern)
  
  for(i in 1:length(names(dat))){
    dat[[i]]$Sample <- paste(word(names(dat)[[i]], c(1), sep = fixed ('.')))
  }
  
  return(dat)
}

# plots 
plot <- function(dat, x_var, y_var, xlabel, ylabel, group_var){
  
  x_var <- rlang::sym(quo_name(enquo(x_var)))
  y_var <- rlang::sym(quo_name(enquo(y_var)))
  group_var <- rlang::sym(quo_name(enquo(group_var)))
  
  p <- ggplot(dat, aes(x = reorder( !! x_var, - !!y_var), y = !!y_var)) + 
    geom_boxplot() +
    geom_jitter(aes(color = !!group_var), shape=16, position=position_jitter(0.2)) +
    theme_bw() +
    #theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
    scale_y_continuous(labels = comma) + 
    labs(x = xlabel, y = ylabel) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title.y = element_text(margin = margin(t = 0, r = 15 , b = 0, l = 0))) 
  
  
  return(p)
  
}
```
```{r data_wrangle, warning=FALSE}
####################### LIMA
# Extract only values from the mix of values and percentage from LIMA output
LIMA_values <- 
  data.frame(LIMA[,1],lapply(LIMA[,2:ncol(LIMA)], 
                                          function(x) as.numeric(word(x, c(1),  sep = fixed ('(')) ))) 
colnames(LIMA_values)[1] <- "Description"


# Extract only percentages from the mix of values and percentage from LIMA output
LIMA_perc <- data.frame(LIMA_values[c(5:14),1])
for(i in 2:NCOL(LIMA)){
  total_num <- LIMA_values[3,i]
  LIMA_perc[,i] <- round(LIMA_values[c(5:14),i]/total_num *100,2)
}
colnames(LIMA_perc) <- colnames(LIMA_values)

# Refine into one dataframe and data-wrangled for easy merging
REFINE <- do.call("rbind", REFINE_list) %>%
  remove_rownames(.) %>%
  column_to_rownames(., var = "Sample") %>%
  t(.) %>%
  as.data.frame() %>%
  rownames_to_column(., var = "Description")


Reads <-   
  data.frame(lapply(CCS[, seq(2, ncol(CCS), 2)], function(x) sum(x))) %>%
  bind_rows(LIMA_values[1,],REFINE) %>%
  mutate(Description = c("Polymerase Reads","CCS Reads", "FL Reads","FLNC reads", "Poly-A FLNC reads")) %>%
  .[,c(ncol(.),1:ncol(.)-1)]

```
```{r create_plots, warning = FALSE}
############# Applying plots

# p1: Number of polymerase reads failed and successulf for CCS generation
# p2: Percentage of polymerase reads failed and successulf for CCS generation
# p3: Summary of CCS reads failed and successful for LIMA filtering
# p4: Number of CCS reads failed 
# p5: Percentage of CCS reads failed

p1 <- 
  # Extract only CCS even columns with values
  CCS[, -seq(3, ncol(CCS) + 1, 2)] %>%
  # Remove all rows with 0 values
  .[apply(.[,-1], 1, function(x) !all(x==0)),] %>%
  # Data wrangle from wide to long for plot
  gather(., Samples, Num_Reads, 2:ncol(.), factor_key=TRUE) %>%
  plot(.,"ZMW.Yield","Num_Reads", "", "Number of Polymerase Reads", Samples)

p2 <- 
  # Extract only CCS odd columns with percentages
  CCS[, seq(1, ncol(CCS) + 1, 2)] %>%
  # Data wrange from wide to long for plot
  gather(., Samples, Num_Reads, 2:ncol(.), factor_key=TRUE) %>% 
  # Remove percentage signs, extract numbers 
  mutate(Num_Reads = as.numeric(gsub("[\\%,]", "", Num_Reads))) %>%
  # Remove columns with 0 reads for ease of plotting
  filter(Num_Reads > 1) %>%
  plot(., "ZMW.Yield","Num_Reads","", "Percentage of Polymerase Reads", Samples)

p3 <- 
  # Working with rows 2 and 3 of LIMA values (summary)
  LIMA_values[c(2,3),] %>%
  # Data wrangle from wide to long for plot
  gather(., Samples, Num_Reads, 2:ncol(LIMA_values), factor_key=TRUE) %>%
  plot(., "Description","Num_Reads","","Number of CCS Reads", Samples)


p4 <-
  # Working with rows 5-14 of LIMA values (summary) involving why reads failed in LIMA
  LIMA_values[c(5:14),] %>% 
  gather(., Samples, Num_Reads, 2:ncol(LIMA_values), factor_key=TRUE) %>%
  plot(., "Description","Num_Reads","","Number of CCS Reads", Samples)

p5 <- 
  # Working with percentages and data wrangle for plot
  LIMA_perc %>%
  gather(., Samples, Perc_Reads, 2:ncol(LIMA_perc), factor_key=TRUE) %>%
  plot(.,"Description","Perc_Reads", "", "Percentage of Polymerase Reads", Samples)

p6 <- 
  Reads %>%
  gather(., Samples, Reads, 2:ncol(.), factor_key=TRUE) %>%
  plot(.,"Description","Reads", "", "Number of Reads", Samples)
```
```{r print_plots}
p1
p2
p3
p4
p5
p6
```