---
title: "Targeted vs Whole Comparison"
author: Szi Kay Leung
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: true
    highlight: tango
    code_folding: hide
    fig_caption: true
    cards: true



---
```{r setup, include=FALSE, results="hide"}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE ,fig.width=15, fig.height= 11.5)

#source("/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Scripts/IsoSeq_Tg4510/Rmarkdown_Input.R")
```
```{r input, results="hide"}
#********************** Variables and input files
output_dir <- "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Isoseq_Paper/QC_Plots"

# INPUT: WHOLE TRANSCRITPOME: SQANTI FILTERED DATA!!!
mouse.whole_class.file_name <- "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/WholeTranscriptome/WT8_ISOSEQ/IsoSeq3.1.2/SQANTI2/WT8IsoSeq.collapsed.filtered.rep_classification.filtered_lite_classification.txt"

# INPUT: TARGETED TRANSCRITPOME: SQANTI FILTERED DATA!!!
mouse.targeted_class.file_name <- "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Targeted/Targeted_Seq_1/SQANTI2/TargetedSeq1.collapsed.filtered.rep_classification.filtered_lite_classification.txt"


#********************** Apply function to datasets 
source("/gpfs/ts0/home/sl693/Scripts/human_mouse_isoseq/DownStream/SQANTI_Further_Characterisation/SQANTI_General.R")

# SQANTI_class_preparation(input.class.file, output.class.file)
# According to SQANTI_report2.R (version 8.7) to prepare classification file in terms of ID columns etc 
mouse.whole_class.file <- SQANTI_class_preparation(mouse.whole_class.file_name)
mouse.targeted_class.file <- SQANTI_class_preparation(mouse.targeted_class.file_name)
mouse.chained_class.file <- SQANTI_class_preparation(mouse.chained_class.file_name)

mytheme <- theme(axis.line = element_line(colour = "black"),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.border = element_blank(),
                 panel.background = element_blank(),
                 text=element_text(size=20,  family="ArialMT"),
                 axis.title.x = element_text(vjust=-0.5, colour = "black"),
                 axis.title.y = element_text(vjust=0.5, margin = margin(t = 0, r = 10, b = 0, l = 0)),
                 #legend.position = c(.90, 0.95),
                 #legend.justification = c(1,1),
                 legend.box.just = "right",
                 legend.margin = margin(6, 6, 6, 6), 
                 legend.text = element_text(size = 20), 
                 legend.position="bottom")

# Capitalise gene names 
mouse.whole_class.file$associated_gene <- toupper(mouse.whole_class.file$associated_gene)
mouse.targeted_class.file$associated_gene <- toupper(mouse.targeted_class.file$associated_gene)
mouse.chained_class.file$associated_gene <- toupper(mouse.chained_class.file$associated_gene)

targeted_genes <- c("APP", "CLU", "APOE", "MAPT", "BIN1", "SORL1",  
                    "PICALM", "PTK2B", "ABCA7", "TREM2", "CD33")

```
