---
raw_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Targeted_Transcriptome/rawdata"
cupcake_sequence: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/softwares/Post_Isoseq3/cDNA_Cupcake/sequence"
sqanti: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/softwares/SQANTI3"

isoseq_output_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Targeted_Transcriptome/IsoSeq"
post_isoseq_output_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Targeted_Transcriptome/Pooled_Samples"

transcriptome: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/reference_2019/mm10.fa"
annotation: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/reference_2019/gencode.vM22.annotation.gtf"

samples:
    TS1: m54082_191116_131337.subreads.bam   #1.Targeted_Sequencing_1: K20, K18, K23, K21, K19, K17 (Project_10040)
    TS2: m54082_200731_163617.subreads.bam   #2.Targeted_Sequencing_2: S19, K24, L22, M21, O18, O23, O22, P19, T20 (Project_10175)
    TS3a: m54082_200801_130641.subreads.bam  #3a.Targeted_Sequencing_3: Q20, Q21, S18, S23, Q18, Q17, L18, Q23, T18 (partial run, Project_10175)
    TS3b: m54082_200808_064617.subreads.bam  #3b.Targeted_Sequencing_3: Q20, Q21, S18, S23, Q18, Q17, L18, Q23, T18 (complete run, Project_10175)

## CCS Parameters
ccs_passes: 1

## LIMA, REFINE Parameters
primer_fasta: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/reference_2019/targeted.primer.fasta"

## Chaining
chain_config: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/Scripts/IsoSeq_Tg4510/1_Transcriptome_Annotation/Snakemake/Chain_Configuration.txt"

RNASeq_Filtered_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/RNASeq/all_filtered/Tg4510_filtered"
RNASeq_STAR_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Testing/RNASeq"

RNASeq_Expression_Samples: [Q21 O18 L22 K18 O23 S23 S18 K17 M21 K23 Q20 K24]
RNASeq_STAR_files: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/Q21/Q21.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/O18/O18.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/L22/L22.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/K18/K18.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/O23/O23.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/S23/S23.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/S18/S18.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/K17/K17.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/M21/M21.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/K23/K23.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/Q20/Q20.SJ.out.bed,\
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Individual_Samples/RNASeq/K24/K24.SJ.out.bed"

cage_peaks: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/reference_2019/CAGE/mm10.cage_peak_phase1and2combined_coord.bed"
polyA_motif: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/softwares/Post_Isoseq3/human.polyA.list.txt"

Kallisto_Output_Name: "All"
