---
raw_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Rawdata"
cupcake_sequence: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/softwares/Post_Isoseq3/cDNA_Cupcake/sequence"
sqanti: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/softwares/SQANTI3"

refine_input_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/IsoSeq/REFINE"
isoseq_output_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Testing"
post_isoseq_output_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/IsoSeq/Whole_Transcriptome/Testing"

transcriptome: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/reference_2019/mm10.fa"
annotation: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/reference_2019/gencode.vM22.annotation.gtf"

samples:
    K18: m54082_180607_173058.subreads.bam
    O18: m54082_180605_141944.subreads.bam

## CCS Parameters
ccs_passes: 1

## LIMA, REFINE Parameters
primer_fasta: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/reference_2019/primer.fasta"
