---
# Szi Kay Leung
# config file for snakemake using RNA-Seq fastq (filtered) as input to map to Iso-Seq as scaffold 

transcriptome: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/WholeTranscriptome/Tg4510/All_Merged/TOFU/mm10/All_Merged.collapsed.filtered.rep.fa"

annotation: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/WholeTranscriptome/Tg4510/All_Merged/TOFU/mm10/All_Merged.collapsed.filtered.gff"

input_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/RNASeq/all_filtered/Tg4510_filtered/MERGED"
output_dir: "/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/WholeTranscriptome/Tg4510/Diff_Analysis/DTU/Isoseq_Rnaseq"    

Samples:
    - "WT":   # this is a group 
        A1: "K24_Merged.fastq.filtered"    # filename pairs must be maintained - identifier and filename
        A2: "K17_Merged.fastq.filtered"
     

    - "TG":  # this is another group - names are arbitrary but must be unique
        B1: "L21_Merged.fastq.filtered"
        B2: "L22_Merged.fastq.filtered"


referenceGroup: "WT"   # this name *must* match one of the group names  

minimap_index_opts: ""

minimap2_opts: ""

maximum_secondary: 100

secondary_score_ratio: 1.0

salmon_libtype: "SF"

# Count filtering options - customize these according to your experimental design:

# Genes expressed in minimum this many samples:
min_samps_gene_expr: 3
# Transcripts expressed in minimum this many samples:
min_samps_feature_expr: 1
# Minimum gene counts:
min_gene_expr: 10
# Minimum transcript counts:
min_feature_expr: 3


lfcThreshold : 1            # minimum required log2 fold change for differential expression analysis
adjPValueThreshold: 0.05    # adjusted p-value threshold for differential expression analysis


threads: 50
tutorialText: TRUE


