---
title: "R Notebook"
output: html_notebook
---
```{r}
# Input: Isabel list of Tg4510 Sample ID and Cummerbund ID
Names <- read.csv("//isad.isadroot.ex.ac.uk/UOE/User/My Documents/PacBio/AD_Mouse_Tg4510/Sample Selection/Tg4510_samples_table.csv",header = TRUE)[,2:3]

head(Names)

# Remove Bad samples from the input 
bad <- c("L19","L20","K22","P22","O17","U26")
Names <- dplyr:: filter(Names, !grepl(paste(bad,collapse="|"), Names$Sample.ID))

# from long to wide for downstream input of rawcount data
library(tidyr)
Names<- Names %>% spread(Sample.ID, Cummerbund.ID, fill = NA, convert = FALSE)
rownames(Names) <- "Condition"

```

```{r}
RNAseq <- read.csv("//isad.isadroot.ex.ac.uk/UOE/User/My Documents/PacBio/AD_Mouse_Tg4510/countdata_ordered_Tg4510.csv", row.names = 1, header = TRUE)

Merge <- rbind(RNAseq,Names)
```

```{r,warning = FALSE}
library(stringr)
WT <- Merge[,which(word(Merge["Condition",],2,sep = fixed ('_')) =="WT")]
WT_2months <- WT[,which(word(WT["Condition",],3,sep = fixed ('_')) =="2m")]
WT_4months <- WT[,which(word(WT["Condition",],3,sep = fixed ('_')) =="4m")]
WT_6months <- WT[,which(word(WT["Condition",],3,sep = fixed ('_')) =="6m")]
WT_8months <- WT[,which(word(WT["Condition",],3,sep = fixed ('_')) =="8m")]

TG <- Merge[,which(word(Merge["Condition",],2,sep = fixed ('_')) =="TG")]
TG_2months <- TG[,which(word(TG["Condition",],3,sep = fixed ('_')) =="2m")]
TG_4months <- TG[,which(word(TG["Condition",],3,sep = fixed ('_')) =="4m")]
TG_6months <- TG[,which(word(TepG["Condition",],3,sep = fixed ('_')) =="6m")]
TG_8months <- TG[,which(word(TG["Condition",],3,sep = fixed ('_')) =="8m")]

dfList <- list(WT_2months,WT_4months,WT_6months,WT_8months,TG_2months,TG_4months,TG_6months,TG_8months)

result_list <- list()

for (i in seq(dfList)){assign(paste0("df",i)) dfList[[i]])
}

results = list()

for (i in 1:length(dfList)){
  dat <- data.matrix(dfList[[i]])
  avg <- apply(dat,1,mean)
  dat <- cbind(dat, avg)
  print(head(dat))
  results[[i]] <- dat
}
  


for (i in 1:length(dfList)){
  result <- data.frame(){
    for (rows in nrows(4)){
    
  }
  avg <- apply(dfList[i],1,mean)
  complete <- data.frame(cbind(dfList[i], avg))
  result_list[i] <- complete
}
result_list



w <- data.frame(cbind(w,mean))
WT_2months <- data.matrix(WT_2months)
mean <- data.frame(apply(WT_2months,1,mean))
WT_2months <- data.frame(cbind(WT_2months,mean))
WT_2months <- WT_2months[order(-WT_2months$apply.WT_2months..1..mean.),]
  
list2env(dfList ,.GlobalEnv)  

```

